/*
 * Here comes the text of your license
 * Each line should be prefixed with  * 
 */
package dae.fxcreator.node.graph;

/**
 * Offers a structured view of the class or shader. This view shows the methods
 * and member variables that are available for the shader or class.
 * @author Koen Samyn
 */
public class StructureView extends javax.swing.JPanel {

    /**
     * Creates new form StructureView
     */
    public StructureView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrMemberList = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        pnlButtons = new javax.swing.JPanel();
        btnAddFunction = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        scrMemberList.setViewportView(jList1);

        add(scrMemberList, java.awt.BorderLayout.CENTER);

        pnlButtons.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnAddFunction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dae/images/add.png"))); // NOI18N
        pnlButtons.add(btnAddFunction);

        btnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dae/images/delete.png"))); // NOI18N
        pnlButtons.add(btnRemove);

        add(pnlButtons, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFunction;
    private javax.swing.JButton btnRemove;
    private javax.swing.JList jList1;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JScrollPane scrMemberList;
    // End of variables declaration//GEN-END:variables
}
