/* Generated By:JavaCC: Do not edit this line. TemplateParserConstants.java */
package dae.fxcreator.io.templates.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TemplateParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int InsertBegin = 5;
  /** RegularExpression Id. */
  int CodeEnd = 6;
  /** RegularExpression Id. */
  int CodeBegin = 7;
  /** RegularExpression Id. */
  int IDENTIFIER = 8;
  /** RegularExpression Id. */
  int LETTER = 9;
  /** RegularExpression Id. */
  int DIGIT = 10;
  /** RegularExpression Id. */
  int SEPARATOR = 11;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"<%=\"",
    "\"%>\"",
    "\"<%\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<SEPARATOR>",
  };

}
